language: java
sudo: required

jdk:
  - oraclejdk8
  
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: 732d011b-d443-4d7d-9c7f-cc43fea577dd
  app:    
    grupo-f-012017 
    
    
before_install:
- cd desapp-groupF-backend

script:
    - mvn clean install -Dmaven.compiler.target=1.8 -Dmaven.compiler.source=1.8
    - mvn clean verify
after_success:
    - mvn clean test jacoco:report coveralls:report
    - cd ..
    - heroku buildpacks:clear
