language: java

jdk:
  - oraclejdk8
  
deploy:
  provider: heroku
  api_key:
    secure: 732d011b-d443-4d7d-9c7f-cc43fea577dd
  app:
    master: grupo-f-012017
    
    
before_install:
- cd desapp-groupF-backend

install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test jacoco:report
after_success:
  - mvn clean test jacoco:report coveralls:report
  - mvn coveralls:report
